#! /bin/bash
#PBS -l	nodes=2:ppn=16,walltime=00:10:00
#PBS -q	debug_gpu
#PBS -m	ae
#PBS -o	out.log
#PBS -e	err.log
#PBS -N	Test_Job

# below are the modules you will need to compile the code on bigred2 (see README)
# uncomment the following 3 lines to load the modules at the time of job launch
module swap PrgEnv-cray PrgEnv-gnu
module load boost/1.65.0
module load gsl

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=16
# -d refers to number of cores. this should match ppn in Line 2.
time aprun -n 2 -d 16 ./np_shape_lab -R 10 -q 600 -c 0.005 -t 1 -v 1 -b 40 -s 40 -S 25000 -D 4 -F n
