name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      BOOST_LIBDIR: /usr/lib/x86_64-linux-gnu/
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests g++ python-dev python3-dev python3-pip maven libnuma-dev libc-dev python3-venv  openmpi-bin libopenmpi-dev flex bison libomp-dev gsl-bin libgsl0-dev libboost-all-dev imagemagick-6.q16 inkscape
      - name: build cpp
        run: make all
      - name: test
        run: cd bin && ./test.sh
